--- 
env:
  es6: true

plugins:
 - 'flowtype'

extends:
 - 'eslint:recommended'
 - 'plugin:flowtype/recommended'

parser: 'babel-eslint'
parserOptions:
  sourceType: 'module'

rules: 
 comma-style: [2, 'first']
 indent: [2, 2, {ArrayExpression: 2, ObjectExpression: 1, SwitchCase: 1}]
 linebreak-style: [2, 'unix']
 no-unused-vars: [2, {argsIgnorePattern: '^_' }]
 no-trailing-spaces: [2]
 quotes: [2, 'single']
 semi: [2, 'always']

 flowtype/space-after-type-colon: [0]
 flowtype/boolean-style: [2, 'bool']
 flowtype/union-intersection-spacing: [0]

